### PR TITLE
Add Region Support with region flag

### PR DESCRIPTION
**Pull request by martynbristow**
Usage: `civo(TOKEN, region='SVG1')`

### CODE REVIEW

**Comment by alejandrojnm** [comment]
I haven't programmed in python for a while haha, I think it's great that I have done this update 👍 , but I think it would be better if we do it in the style of the Go library, that it is possible to pass the region to any of the classes, like: 

```python
# this is a global declaration
civo = Civo('token', region='NYC1')

# this is a service declaration
civo.kubernetes.create(name='my_cluster', num_nodes=2, region='SVG1')
```
in both case region is optional

**Comment by martynbristow** [comment]
Yeah I can update it to that, was keen to get something moving

**Comment by martynbristow** [comment]
Need to complete some tests and verify I've covered everything.
Kubernetes is working ok

**Comment by alejandrojnm** [comment]
Look good to me. Also you add the test unit, the first time I didn't have time to do it

**Pull request merged**
